spec:
  name: palmsure
  static_sites:
    - name: palmsure-web
      github:
        repo: HunchoKing/Palmsure
        branch: main
        deploy_on_push: true
      source_dir: /
      environment_slug: static-sites
      build_command: npm install -g pnpm && pnpm install && ng build --configuration production --output-mode static
      output_dir: dist/palmsure-corp-v2/browser
      routes:
        - path: /
